version: '3'
services:
  dns:
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    build: .
    volumes:
      - ./dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - 53:53/udp
      - 5380:8080/tcp
    cap_add:
      - NET_ADMIN
    environment:
      - HTTP_USER=foo
      - HTTP_PASS=bar
